"""changes

Revision ID: 53be7088eced
Revises: 5199d305613c
Create Date: 2025-09-27 21:48:31.870696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53be7088eced'
down_revision = '5199d305613c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
